name: shell commands
on: [push]
jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
      steps:
	- name: echo a string
	  run: echo "hello from github"
        - name: multiline script
          run: |
            node -v
            npm -v
