name: Test build node
on:  push
jobs:
  first-job:
    name: build node
    runs-on: ubuntu-latest
	  container: node:12.18.4
    steps:
      - run: node --version
      - run: npm --version
	    - uses: action/checkout@v2
	    - run: npm install
	
